FROM photoflow/docker-buildenv-mingw-manjaro-base

USER root

RUN echo "[multilib]" >> /etc/pacman.conf && \
  echo "Include = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf && \
  pacman --noconfirm -Syu && pacman --noconfirm -S wine

USER msys2

ADD ./wine-startup-manjaro.tgz /home/msys2
